name: ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-wtf werkzeug

    - name: Initialize the database
      env:
        INIT_DB: "1"
      run: |
        python library_management.py

    - name: Run Flask app in background
      env:
        FLASK_APP: library_management.py
      run: |
        nohup python library_management.py > flask.log 2>&1 &
        sleep 10

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://127.0.0.1:5000'
        format: 'html'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap_scan_report
        path: |
          report_html.html
          report_md.md
          report_json.json
